/*
 * GPIO.c
 *
 *  Created on: Feb 10, 2020
 *      Author: TARGET
 */


#include "GPIO.h"

#define REG volatile unsigned long int *


#define PIN_NUM


void PORTA_COFIG_OUT (PIN_NUM)
{


    REG  GPIODIR =  AB(OFF_GPIODIR);
    REG  GPIOAFSEL= AB(OFF_GPIOAFSEL);
    REG  GPIODR8R = AB(OFF_GPIODR8R);
    REG  GPIODEN=   AB(OFF_GPIODEN);
    REG GPIOPUR =  AB(OFF_GPIOPUR);


    GPIOHBCTL_PORTA;
    RCGCGPIO_PORTA;
    GPIODIR_OUT(PIN_NUM);
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_DIS(PIN_NUM) ;

}


void PORTB_COFIG_OUT (PIN_NUM)
{


    REG  GPIODIR =  BB(OFF_GPIODIR);
    REG  GPIOAFSEL= BB(OFF_GPIOAFSEL);
    REG  GPIODR8R = BB(OFF_GPIODR8R);
    REG  GPIODEN=   BB(OFF_GPIODEN);
    REG GPIOPUR =  BB(OFF_GPIOPUR);


    GPIOHBCTL_PORTB;
    RCGCGPIO_PORTB;
    GPIODIR_OUT(PIN_NUM);
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_DIS(PIN_NUM) ;

}


void PORTC_COFIG_OUT (PIN_NUM)
{


    REG  GPIODIR =  CB(OFF_GPIODIR);
    REG  GPIOAFSEL= CB(OFF_GPIOAFSEL);
    REG  GPIODR8R = CB(OFF_GPIODR8R);
    REG  GPIODEN=   CB(OFF_GPIODEN);
    REG GPIOPUR =   CB(OFF_GPIOPUR);


    GPIOHBCTL_PORTC;
    RCGCGPIO_PORTC;
    GPIODIR_OUT(PIN_NUM);
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_DIS(PIN_NUM) ;

}


void PORTD_COFIG_OUT (PIN_NUM)
{


    REG  GPIODIR =  DB(OFF_GPIODIR);
    REG  GPIOAFSEL= DB(OFF_GPIOAFSEL);
    REG  GPIODR8R = DB(OFF_GPIODR8R);
    REG  GPIODEN=   DB(OFF_GPIODEN);
    REG GPIOPUR =   DB(OFF_GPIOPUR);


    GPIOHBCTL_PORTD;
    RCGCGPIO_PORTD;
    GPIODIR_OUT(PIN_NUM);
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_DIS(PIN_NUM) ;

}


void PORTE_COFIG_OUT (PIN_NUM)
{


    REG  GPIODIR =  EB(OFF_GPIODIR);
    REG  GPIOAFSEL= EB(OFF_GPIOAFSEL);
    REG  GPIODR8R = EB(OFF_GPIODR8R);
    REG  GPIODEN=   EB(OFF_GPIODEN);
    REG GPIOPUR =   EB(OFF_GPIOPUR);


    GPIOHBCTL_PORTE;
    RCGCGPIO_PORTE;
    GPIODIR_OUT(PIN_NUM);
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_DIS(PIN_NUM) ;

}


void PORTF_COFIG_OUT (PIN_NUM)
{


    REG  GPIODIR =  FB(OFF_GPIODIR);
    REG  GPIOAFSEL= FB(OFF_GPIOAFSEL);
    REG  GPIODR8R = FB(OFF_GPIODR8R);
    REG  GPIODEN=   FB(OFF_GPIODEN);
    REG GPIOPUR =   FB(OFF_GPIOPUR);


    GPIOHBCTL_PORTF;
    RCGCGPIO_PORTF;
    GPIODIR_OUT(PIN_NUM);
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_DIS(PIN_NUM) ;

}






void PORTA_COFIG_IN (PIN_NUM)
{


    REG  GPIODIR =  AB(OFF_GPIODIR);
    REG  GPIOAFSEL= AB(OFF_GPIOAFSEL);
    REG  GPIODR8R = AB(OFF_GPIODR8R);
    REG  GPIODEN=   AB(OFF_GPIODEN);
    REG GPIOPUR =   AB(OFF_GPIOPUR);


    GPIOHBCTL_PORTA;
    RCGCGPIO_PORTA;

    GPIODIR_IN(PIN_NUM)
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_EN(PIN_NUM) ;
}

void PORTB_COFIG_IN (PIN_NUM)
{


    REG  GPIODIR =  BB(OFF_GPIODIR);
    REG  GPIOAFSEL= BB(OFF_GPIOAFSEL);
    REG  GPIODR8R = BB(OFF_GPIODR8R);
    REG  GPIODEN=   BB(OFF_GPIODEN);
    REG GPIOPUR =   BB(OFF_GPIOPUR);


    GPIOHBCTL_PORTB;
    RCGCGPIO_PORTB;

    GPIODIR_IN(PIN_NUM)
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_EN(PIN_NUM) ;
}


void PORTC_COFIG_IN (PIN_NUM)
{


    REG  GPIODIR =  CB(OFF_GPIODIR);
    REG  GPIOAFSEL= CB(OFF_GPIOAFSEL);
    REG  GPIODR8R = CB(OFF_GPIODR8R);
    REG  GPIODEN=   CB(OFF_GPIODEN);
    REG GPIOPUR =   CB(OFF_GPIOPUR);


    GPIOHBCTL_PORTC;
    RCGCGPIO_PORTC;

    GPIODIR_IN(PIN_NUM)
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_EN(PIN_NUM) ;
}

void PORTD_COFIG_IN (PIN_NUM)
{


    REG  GPIODIR =  DB(OFF_GPIODIR);
    REG  GPIOAFSEL= DB(OFF_GPIOAFSEL);
    REG  GPIODR8R = DB(OFF_GPIODR8R);
    REG  GPIODEN=   DB(OFF_GPIODEN);
    REG GPIOPUR =   DB(OFF_GPIOPUR);


    GPIOHBCTL_PORTD;
    RCGCGPIO_PORTD;

    GPIODIR_IN(PIN_NUM)
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_EN(PIN_NUM) ;
}


void PORTE_COFIG_IN (PIN_NUM)
{


    REG  GPIODIR =  EB(OFF_GPIODIR);
    REG  GPIOAFSEL= EB(OFF_GPIOAFSEL);
    REG  GPIODR8R = EB(OFF_GPIODR8R);
    REG  GPIODEN=   EB(OFF_GPIODEN);
    REG GPIOPUR =   EB(OFF_GPIOPUR);


    GPIOHBCTL_PORTE;
    RCGCGPIO_PORTE;

    GPIODIR_IN(PIN_NUM)
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_EN(PIN_NUM) ;
}
void PORTF_COFIG_IN (PIN_NUM)
{


    REG  GPIODIR =  FB(OFF_GPIODIR);
    REG  GPIOAFSEL= FB(OFF_GPIOAFSEL);
    REG  GPIODR8R = FB(OFF_GPIODR8R);
    REG  GPIODEN=   FB(OFF_GPIODEN);
    REG GPIOPUR =   FB(OFF_GPIOPUR);


    GPIOHBCTL_PORTF;
    RCGCGPIO_PORTF;

    GPIODIR_IN(PIN_NUM);
    GPIOAFSEL_GPIO;
    GPIODR8R_8MA;
    GPIOD_EN;
    GPIO_PUR_EN(PIN_NUM) ;
}
